fix_seed: 0
model_path: best_model_13ptm_final.pth
data_path: Phosphorylation_S_sequence.fasta

encoder:
  model_name: facebook/esm2_t33_650M_UR50D    #  esmc_600m  #facebook/esm2_t33_650M_UR50D # facebook/esm2_t33_650M_UR50D, facebook/esm2_t30_150M_UR50D, facebook/esm2_t12_35M_UR50D, facebook/esm2_t6_8M_UR50D, Rostlab/prot_t5_base_mt_uniref50
  max_len: 1024
  tune_embedding: False
  adapter_h:
    enable: True
    num_end_adapter_layers: [12]    #splm-[12],esm2[0]
    module_type: "MLP1"
    freeze_adapter_layers: [True]   #splm-[True],esm2[False]
  fine_tune:
    enable: False
    last_layers_trainable: 2
    freeze_adapter_layers: [False]
  lora:
    enable: False
    r: 2
    lora_alpha: 8
    lora_dropout: 0.05
    esm_num_end_lora: 33
  prompt:
    enable: True
    prompt_addition_enable: False
    prompt_predefined_enable: True
    prompt_len: 500   #todo  3
    prompt_layer_indices: [0]
    num_tasks: 13    #todo 4 19
    task_token_path: ./esm_adapterH/
#    ./new_uniprot_data/9-s_plm_task_token_cluster_embeddings/average
#
    if_pass_to_MHA: False
    if_attention_masks: False
    if_weighted_skip_connection: False
    if_grads: True
  input_type: protein_sequence #peptide  or protein_sequence
  num_classes: 2
#  head_dropout: 0.3
#  mlp_hidden_dim: 100
#  mlp_layer_num: 2

projector:
  projector_type: CNN #or CNN or MLP or Transformer MHACustom
  droprate: 0.75
  kernel_sizes: [1,9,11]
  out_channels: 200
  output_dim: 2
  inner_linear_dim: 128
  num_layers: 2
  mhc_number: 2
  if_flattern: False
  if_frozen: False
  if_multihead: True


test_settings:
  data_path: ./uniprot_data_2010_as_timestamp/6-final_csv/test/
#  ./new_uniprot_data/7-final_csv/test/
#    #todo
  batch_size: 64
  device: cuda
  num_workers: 0

tasks:   #todo 7
  Phosphorylation_S: True
  Phosphorylation_T: True
  Phosphorylation_Y: True
  Ubiquitination_K: True
  Acetylation_K: True
  OlinkedGlycosylation_S: True
  Methylation_R: True
  NlinkedGlycosylation_N: True
  OlinkedGlycosylation_T: True
  Methylation_K: True
  Palmitoylation_C: True
  Sumoylation_K: True
  Succinylation_K: True

task_ids:   #todo 8
  Phosphorylation_S: 0
  Phosphorylation_T: 1
  Phosphorylation_Y: 2
  Ubiquitination_K: 3
  Acetylation_K: 4
  OlinkedGlycosylation_S: 5
  Methylation_R: 6
  NlinkedGlycosylation_N: 7
  OlinkedGlycosylation_T: 8
  Methylation_K: 9
  Palmitoylation_C: 10
  Sumoylation_K: 11
  Succinylation_K: 12



